# Generated by Django 4.2.7 on 2023-11-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wish', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
            ],
        ),
    ]
